# Generated by Django 4.2.7 on 2026-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ (ссылка)')),
                ('preview', models.TextField(max_length=300, verbose_name='Анонс')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сравнительная статья',
                'verbose_name_plural': 'Сравнительные статьи',
                'ordering': ['order'],
            },
        ),
    ]
