# Generated by Django 4.2.7 on 2026-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(verbose_name='User-Agent')),
                ('consent_given', models.BooleanField(verbose_name='Согласие дано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Согласие на cookie',
                'verbose_name_plural': 'Согласия на cookie',
                'ordering': ['-created_at'],
            },
        ),
    ]
