# Generated by Django 4.2.7 on 2026-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('category', models.CharField(choices=[('stories', 'Истории'), ('codex', 'Кодекс'), ('reviews', 'Разборы'), ('books', 'Книжная полка'), ('video', 'Видео'), ('about', 'Кто я')], max_length=20, verbose_name='Рубрика')),
                ('content', models.TextField(verbose_name='Текст')),
                ('preview', models.TextField(max_length=300, verbose_name='Анонс')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'Блог',
                'ordering': ['-created_at'],
            },
        ),
    ]
