# Generated by Django 5.2.17 on 2026-08-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('code', models.CharField(max_length=20, verbose_name='Код (FXD, FXDB и т.д.)')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ (ссылка)')),
                ('years', models.CharField(max_length=50, verbose_name='Годы выпуска')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/', verbose_name='Фото')),
                ('photo_credit', models.CharField(blank=True, max_length=200, verbose_name='Автор фото')),
                ('is_predecessor', models.BooleanField(default=False, verbose_name='Это предшественник? (FXR)')),
                ('previous_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike', verbose_name='Предшественник (если есть)')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
            },
        ),
    ]
